spin_manifest_version = 2

[application]
name = "spin-s3-example"
version = "0.1.0"
authors = ["Adam Reese <adam@reese.io>"]
description = "Example Spin application using S3 client."

[[trigger.http]]
route = "/..."
component = "spin-s3-example"

[component.spin-s3-example]
source = "main.wasm"
allowed_outbound_hosts = [
  "http://s3.localhost.localstack.cloud:4566",
  "https://s3.us-east-1.amazonaws.com",
]

[variables]
s3_access_key_id = { default = "" }
s3_secret_access_key = { default = "" }
s3_session_token = { default = "" }
s3_region = { default = "us-east-1" }
s3_endpoint = { default = "" }

[component.spin-s3-example.variables]
s3_access_key_id = "{{s3_access_key_id}}"
s3_secret_access_key = "{{s3_secret_access_key}}"
s3_session_token = "{{s3_session_token}}"
s3_region = "{{s3_region}}"
s3_endpoint = "{{s3_endpoint}}"

[component.spin-s3-example.build]
command = "tinygo build -target=wasi -gc=leaking -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]
