spin_manifest_version = 2

[application]
name = "spin-s3-example"
version = "0.1.0"
authors = ["Adam Reese <adam@reese.io>"]
description = "Example Spin application using S3 client."

[[trigger.http]]
route = "/..."
component = "spin-s3-example"

[component.spin-s3-example]
source = "main.wasm"
allowed_outbound_hosts = [
  "http://s3.localhost.localstack.cloud:4566",
  "https://s3.us-east-1.amazonaws.com",
]

[variables]
aws_access_key_id = { required = true }
aws_secret_access_key = { required = true }
aws_session_token = { required = true }
aws_default_region = { required = true }

[component.spin-s3-example.variables]
aws_access_key_id = "{{aws_access_key_id}}"
aws_secret_access_key = "{{aws_secret_access_key}}"
aws_session_token = "{{aws_session_token}}"
aws_default_region = "{{aws_default_region}}"

[component.spin-s3-example.build]
command = "tinygo build -target=wasi -gc=leaking -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]
